#include "omp.h"

#include "emmintrin.h"
#include "nmmintrin.h"
#include "immintrin.h"

#include "defs.h"

// sort 2 32*8 bit vector registers
#define sort_two_vectors(a, b, tmp) \
	(tmp) = _mm256_min_epu8 ((a), (b)); \
	(a) = _mm256_max_epu8 ((a), (b)); \
	(b) = (tmp);

void median_filter_avx(int imgHeight, int imgWidth, int imgWidthF,
				unsigned char *imgSrcExt, unsigned char *imgDst)
{

#if USE_OMP==1
	#pragma omp parallel for
#else
#endif
	for (int row = 0; row < imgHeight; row++)
	{
		// step with the width of one vector reg
		for (int col = 0; col < imgWidth*3; col += 32)
		{
			/*
			 * load 25 vector registers
			 * sort vector regs
			 * 32 median values are 32 outputs
			 */

			// buffer to hold 5x5 filter input pixels
			__m256i filterbuffer[25] = {};
			__m256i tmp = _mm256_set1_epi8(0);


			/*
			 *	load indexes generated by python script
			 */

		#if LOOP_UNROLL == 1
			unsigned char* pixel_addr;
			#include "unrolled_load_loop.txt"
		#else
			for (int fy = 0; fy < FILTER_H; fy++)
			{
				for (int fx = 0; fx < FILTER_W; fx++)
				{
					int filter_idx = fy * FILTER_W + fx;
					unsigned char* pixel_addr = (imgSrcExt + (row + fy) * imgWidthF * 3 + col + fx * 3);
					filterbuffer[filter_idx] = _mm256_lddqu_si256((__m256i*)(pixel_addr));
				}
			}
		#endif // LOOP_UNROLL

			// manually writing which elements to sort
			// to save on execution time (loop unroll),
			// and to easier control which not to calculate
			// - as any sorting after we found the median
			// is an overhead

			/*
			 *	sort indexes generated by python script
			 */

			sort_two_vectors(filterbuffer[1],filterbuffer[0], tmp);
			sort_two_vectors(filterbuffer[3],filterbuffer[2], tmp);
			sort_two_vectors(filterbuffer[5],filterbuffer[4], tmp);
			sort_two_vectors(filterbuffer[7],filterbuffer[6], tmp);
			sort_two_vectors(filterbuffer[9],filterbuffer[8], tmp);
			sort_two_vectors(filterbuffer[11],filterbuffer[10], tmp);
			sort_two_vectors(filterbuffer[13],filterbuffer[12], tmp);
			sort_two_vectors(filterbuffer[15],filterbuffer[14], tmp);
			sort_two_vectors(filterbuffer[17],filterbuffer[16], tmp);
			sort_two_vectors(filterbuffer[19],filterbuffer[18], tmp);
			sort_two_vectors(filterbuffer[21],filterbuffer[20], tmp);
			sort_two_vectors(filterbuffer[23],filterbuffer[22], tmp);
			sort_two_vectors(filterbuffer[2],filterbuffer[0], tmp);
			sort_two_vectors(filterbuffer[3],filterbuffer[1], tmp);
			sort_two_vectors(filterbuffer[6],filterbuffer[4], tmp);
			sort_two_vectors(filterbuffer[7],filterbuffer[5], tmp);
			sort_two_vectors(filterbuffer[10],filterbuffer[8], tmp);
			sort_two_vectors(filterbuffer[11],filterbuffer[9], tmp);
			sort_two_vectors(filterbuffer[14],filterbuffer[12], tmp);
			sort_two_vectors(filterbuffer[15],filterbuffer[13], tmp);
			sort_two_vectors(filterbuffer[18],filterbuffer[16], tmp);
			sort_two_vectors(filterbuffer[19],filterbuffer[17], tmp);
			sort_two_vectors(filterbuffer[22],filterbuffer[20], tmp);
			sort_two_vectors(filterbuffer[23],filterbuffer[21], tmp);
			sort_two_vectors(filterbuffer[2],filterbuffer[1], tmp);
			sort_two_vectors(filterbuffer[6],filterbuffer[5], tmp);
			sort_two_vectors(filterbuffer[10],filterbuffer[9], tmp);
			sort_two_vectors(filterbuffer[14],filterbuffer[13], tmp);
			sort_two_vectors(filterbuffer[18],filterbuffer[17], tmp);
			sort_two_vectors(filterbuffer[22],filterbuffer[21], tmp);
			sort_two_vectors(filterbuffer[4],filterbuffer[0], tmp);
			sort_two_vectors(filterbuffer[5],filterbuffer[1], tmp);
			sort_two_vectors(filterbuffer[6],filterbuffer[2], tmp);
			sort_two_vectors(filterbuffer[7],filterbuffer[3], tmp);
			sort_two_vectors(filterbuffer[12],filterbuffer[8], tmp);
			sort_two_vectors(filterbuffer[13],filterbuffer[9], tmp);
			sort_two_vectors(filterbuffer[14],filterbuffer[10], tmp);
			sort_two_vectors(filterbuffer[15],filterbuffer[11], tmp);
			sort_two_vectors(filterbuffer[20],filterbuffer[16], tmp);
			sort_two_vectors(filterbuffer[21],filterbuffer[17], tmp);
			sort_two_vectors(filterbuffer[22],filterbuffer[18], tmp);
			sort_two_vectors(filterbuffer[23],filterbuffer[19], tmp);
			sort_two_vectors(filterbuffer[4],filterbuffer[2], tmp);
			sort_two_vectors(filterbuffer[5],filterbuffer[3], tmp);
			sort_two_vectors(filterbuffer[12],filterbuffer[10], tmp);
			sort_two_vectors(filterbuffer[13],filterbuffer[11], tmp);
			sort_two_vectors(filterbuffer[20],filterbuffer[18], tmp);
			sort_two_vectors(filterbuffer[21],filterbuffer[19], tmp);
			sort_two_vectors(filterbuffer[2],filterbuffer[1], tmp);
			sort_two_vectors(filterbuffer[4],filterbuffer[3], tmp);
			sort_two_vectors(filterbuffer[6],filterbuffer[5], tmp);
			sort_two_vectors(filterbuffer[10],filterbuffer[9], tmp);
			sort_two_vectors(filterbuffer[12],filterbuffer[11], tmp);
			sort_two_vectors(filterbuffer[14],filterbuffer[13], tmp);
			sort_two_vectors(filterbuffer[18],filterbuffer[17], tmp);
			sort_two_vectors(filterbuffer[20],filterbuffer[19], tmp);
			sort_two_vectors(filterbuffer[22],filterbuffer[21], tmp);
			sort_two_vectors(filterbuffer[8],filterbuffer[0], tmp);
			sort_two_vectors(filterbuffer[9],filterbuffer[1], tmp);
			sort_two_vectors(filterbuffer[10],filterbuffer[2], tmp);
			sort_two_vectors(filterbuffer[11],filterbuffer[3], tmp);
			sort_two_vectors(filterbuffer[12],filterbuffer[4], tmp);
			sort_two_vectors(filterbuffer[13],filterbuffer[5], tmp);
			sort_two_vectors(filterbuffer[14],filterbuffer[6], tmp);
			sort_two_vectors(filterbuffer[15],filterbuffer[7], tmp);
			sort_two_vectors(filterbuffer[24],filterbuffer[16], tmp);
			sort_two_vectors(filterbuffer[8],filterbuffer[4], tmp);
			sort_two_vectors(filterbuffer[9],filterbuffer[5], tmp);
			sort_two_vectors(filterbuffer[10],filterbuffer[6], tmp);
			sort_two_vectors(filterbuffer[11],filterbuffer[7], tmp);
			sort_two_vectors(filterbuffer[24],filterbuffer[20], tmp);
			sort_two_vectors(filterbuffer[4],filterbuffer[2], tmp);
			sort_two_vectors(filterbuffer[5],filterbuffer[3], tmp);
			sort_two_vectors(filterbuffer[8],filterbuffer[6], tmp);
			sort_two_vectors(filterbuffer[9],filterbuffer[7], tmp);
			sort_two_vectors(filterbuffer[12],filterbuffer[10], tmp);
			sort_two_vectors(filterbuffer[13],filterbuffer[11], tmp);
			sort_two_vectors(filterbuffer[20],filterbuffer[18], tmp);
			sort_two_vectors(filterbuffer[21],filterbuffer[19], tmp);
			sort_two_vectors(filterbuffer[24],filterbuffer[22], tmp);
			sort_two_vectors(filterbuffer[2],filterbuffer[1], tmp);
			sort_two_vectors(filterbuffer[4],filterbuffer[3], tmp);
			sort_two_vectors(filterbuffer[6],filterbuffer[5], tmp);
			sort_two_vectors(filterbuffer[8],filterbuffer[7], tmp);
			sort_two_vectors(filterbuffer[10],filterbuffer[9], tmp);
			sort_two_vectors(filterbuffer[12],filterbuffer[11], tmp);
			sort_two_vectors(filterbuffer[14],filterbuffer[13], tmp);
			sort_two_vectors(filterbuffer[18],filterbuffer[17], tmp);
			sort_two_vectors(filterbuffer[20],filterbuffer[19], tmp);
			sort_two_vectors(filterbuffer[22],filterbuffer[21], tmp);
			sort_two_vectors(filterbuffer[24],filterbuffer[23], tmp);
			sort_two_vectors(filterbuffer[16],filterbuffer[0], tmp);
			sort_two_vectors(filterbuffer[17],filterbuffer[1], tmp);
			sort_two_vectors(filterbuffer[18],filterbuffer[2], tmp);
			sort_two_vectors(filterbuffer[19],filterbuffer[3], tmp);
			sort_two_vectors(filterbuffer[20],filterbuffer[4], tmp);
			sort_two_vectors(filterbuffer[21],filterbuffer[5], tmp);
			sort_two_vectors(filterbuffer[22],filterbuffer[6], tmp);
			sort_two_vectors(filterbuffer[23],filterbuffer[7], tmp);
			//sort_two_vectors(filterbuffer[24],filterbuffer[8], tmp);
			sort_two_vectors(filterbuffer[16],filterbuffer[8], tmp);
			sort_two_vectors(filterbuffer[17],filterbuffer[9], tmp);
			sort_two_vectors(filterbuffer[18],filterbuffer[10], tmp);
			sort_two_vectors(filterbuffer[19],filterbuffer[11], tmp);
			sort_two_vectors(filterbuffer[20],filterbuffer[12], tmp);
			sort_two_vectors(filterbuffer[21],filterbuffer[13], tmp);
			//sort_two_vectors(filterbuffer[22],filterbuffer[14], tmp);
			//sort_two_vectors(filterbuffer[23],filterbuffer[15], tmp);
			//sort_two_vectors(filterbuffer[8],filterbuffer[4], tmp);
			//sort_two_vectors(filterbuffer[9],filterbuffer[5], tmp);
			sort_two_vectors(filterbuffer[10],filterbuffer[6], tmp);
			sort_two_vectors(filterbuffer[11],filterbuffer[7], tmp);
			sort_two_vectors(filterbuffer[16],filterbuffer[12], tmp);
			sort_two_vectors(filterbuffer[17],filterbuffer[13], tmp);
			//sort_two_vectors(filterbuffer[18],filterbuffer[14], tmp);
			//sort_two_vectors(filterbuffer[19],filterbuffer[15], tmp);
			//sort_two_vectors(filterbuffer[24],filterbuffer[20], tmp);
			//sort_two_vectors(filterbuffer[4],filterbuffer[2], tmp);
			//sort_two_vectors(filterbuffer[5],filterbuffer[3], tmp);
			//sort_two_vectors(filterbuffer[8],filterbuffer[6], tmp);
			//sort_two_vectors(filterbuffer[9],filterbuffer[7], tmp);
			sort_two_vectors(filterbuffer[12],filterbuffer[10], tmp);
			sort_two_vectors(filterbuffer[13],filterbuffer[11], tmp);
			//sort_two_vectors(filterbuffer[16],filterbuffer[14], tmp);
			//sort_two_vectors(filterbuffer[17],filterbuffer[15], tmp);
			//sort_two_vectors(filterbuffer[20],filterbuffer[18], tmp);
			//sort_two_vectors(filterbuffer[21],filterbuffer[19], tmp);
			//sort_two_vectors(filterbuffer[24],filterbuffer[22], tmp);
			//sort_two_vectors(filterbuffer[2],filterbuffer[1], tmp);
			//sort_two_vectors(filterbuffer[4],filterbuffer[3], tmp);
			//sort_two_vectors(filterbuffer[6],filterbuffer[5], tmp);
			//sort_two_vectors(filterbuffer[8],filterbuffer[7], tmp);
			//sort_two_vectors(filterbuffer[10],filterbuffer[9], tmp);
			sort_two_vectors(filterbuffer[12],filterbuffer[11], tmp);
			//sort_two_vectors(filterbuffer[14],filterbuffer[13], tmp);
			//sort_two_vectors(filterbuffer[16],filterbuffer[15], tmp);
			//sort_two_vectors(filterbuffer[18],filterbuffer[17], tmp);
			//sort_two_vectors(filterbuffer[20],filterbuffer[19], tmp);
			//sort_two_vectors(filterbuffer[22],filterbuffer[21], tmp);
			//sort_two_vectors(filterbuffer[24],filterbuffer[23], tmp);

			// storing 32 outputs
			_mm256_storeu_si256((__m256i*)(imgDst + row * imgWidth * 3 + col), filterbuffer[12]);
		}
	}
}
